#!/usr/bin/env lua

require('extensions')
local u = require('utils')
local Repo = require('repo')
local c = require('colors')

local env = {}
env.home = os.getenv("HOME")

local scanlist = u.make_dict({
  '~/dots',
  '~/dots/personal',
  '~/dots/zsh',
  '~/repos/ags',
  '~/repos/books'
})

local git_repos = {}
local not_repos = {}
for k, _ in pairs(scanlist) do
  local dir = k:gsub('^~', env.home)
  local g = dir .. '/.git'
  if u.exists(g) then
    table.insert(git_repos, dir)
  else
    table.insert(not_repos, dir)
  end
end

local repos = {}
for _, dir in pairs(git_repos) do
  local res = Repo.new(dir)
  if res then
    table.insert(repos, res)
  end
end

local main = function ()
  for _, r in ipairs(repos) do
    local name = c.green(r.name)
    print('\n'..c.gray('[')..name..c.gray('/'..r.branch..']'))
    table.print(r.commits)
    table.print(r.status)
  end
  print()
end

main()
